version: "3.6"
services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
      - /home/app/node_modules
    restart: always
    command: npm run dev
    env_file:
      - ./.env
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env
  graphql-engine:
    container_name: hasura
    image: hasura/graphql-engine:v2.0.9
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    env_file:
      - ./.env
volumes:
  db_data:

