SET check_function_bodies = false;
CREATE TABLE public.address (
    id bigint NOT NULL,
    zip character varying NOT NULL,
    state character varying NOT NULL,
    city character varying NOT NULL,
    neighborhood character varying NOT NULL,
    street character varying NOT NULL,
    number integer NOT NULL,
    complement character varying
);
ALTER TABLE public.address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.category (
    id bigint NOT NULL,
    name character varying NOT NULL
);
ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.cause (
    id bigint NOT NULL,
    name character varying NOT NULL
);
ALTER TABLE public.cause ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cause_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.cause_institution (
    id bigint NOT NULL,
    cause_id integer NOT NULL,
    institution_id integer NOT NULL
);
ALTER TABLE public.cause_institution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cause_institution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.institution (
    id bigint NOT NULL,
    inscription character varying NOT NULL,
    company_name character varying,
    trading_name character varying NOT NULL,
    description text,
    picture character varying,
    pix_key character varying,
    impacted_people integer,
    foundation_date timestamp without time zone DEFAULT now() NOT NULL,
    is_active boolean DEFAULT false NOT NULL,
    other_cause character varying,
    address_id integer,
    user_id integer
);
ALTER TABLE public.institution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.institution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.item (
    id bigint NOT NULL,
    name character varying NOT NULL,
    measure character varying,
    price double precision NOT NULL,
    category_id integer NOT NULL
);
ALTER TABLE public.item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.item_institution (
    id bigint NOT NULL,
    item_id integer NOT NULL,
    institution_id integer NOT NULL
);
ALTER TABLE public.item_institution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_institution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.refresh_token (
    id bigint NOT NULL,
    refresh_token uuid NOT NULL,
    user_agent character varying,
    last_ip character varying,
    expires_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    user_id integer NOT NULL
);
ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public."user" (
    id bigint NOT NULL,
    inscription character varying,
    email character varying NOT NULL,
    phone character varying,
    first_name character varying,
    last_name character varying,
    picture character varying,
    code character varying,
    code_tries integer DEFAULT 0,
    code_expires_at timestamp without time zone DEFAULT now() NOT NULL,
    longitude character varying,
    latitude character varying,
    is_active boolean DEFAULT true NOT NULL,
    address_id integer,
    associated_id integer
);
ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_name_key UNIQUE (name);
ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cause_institution
    ADD CONSTRAINT cause_institution_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cause
    ADD CONSTRAINT cause_name_key UNIQUE (name);
ALTER TABLE ONLY public.cause
    ADD CONSTRAINT cause_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.institution
    ADD CONSTRAINT institution_address_id_key UNIQUE (address_id);
ALTER TABLE ONLY public.institution
    ADD CONSTRAINT institution_inscription_key UNIQUE (inscription);
ALTER TABLE ONLY public.institution
    ADD CONSTRAINT institution_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.institution
    ADD CONSTRAINT institution_user_id_key UNIQUE (user_id);
ALTER TABLE ONLY public.item_institution
    ADD CONSTRAINT item_institution_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.item
    ADD CONSTRAINT item_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_refresh_token_key UNIQUE (refresh_token);
ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_address_id_key UNIQUE (address_id);
ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_email_key UNIQUE (email);
ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_inscription_key UNIQUE (inscription);
ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_phone_key UNIQUE (phone);
ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cause_institution
    ADD CONSTRAINT cause_institution_cause_id_fkey FOREIGN KEY (cause_id) REFERENCES public.cause(id);
ALTER TABLE ONLY public.cause_institution
    ADD CONSTRAINT cause_institution_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.institution(id);
ALTER TABLE ONLY public.institution
    ADD CONSTRAINT institution_address_id_fkey FOREIGN KEY (address_id) REFERENCES public.address(id);
ALTER TABLE ONLY public.institution
    ADD CONSTRAINT institution_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);
ALTER TABLE ONLY public.item
    ADD CONSTRAINT item_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.category(id);
ALTER TABLE ONLY public.item_institution
    ADD CONSTRAINT item_institution_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.institution(id);
ALTER TABLE ONLY public.item_institution
    ADD CONSTRAINT item_institution_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.item(id);
ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);
ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_address_id_fkey FOREIGN KEY (address_id) REFERENCES public.address(id);
ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_associated_id_fkey FOREIGN KEY (associated_id) REFERENCES public.institution(id);
