mutation {
  createUser(
    data: {
      email: "johndoe@gmail.com"
      password: "123"
      firstName: "John"
      lastName: "Doe"
      isAdmin: true
      isSuperAdmin: true
      isActive: true
      address: {
        create: {
          cep: "98700-000"
          state: "Rio Grande do Sul"
          city: "Ijuí"
          neighborhood: "Centro"
          street: "Rua José Bonifácio"
          number: "987"
          complement: "Casa"
        }
      }
    }
  ) {
    _id
    email
    address {
      _id
      cep
    }
  }
}

query {
  findUserByID(id: "311546714668401219") {
    _id
    email
    phone
    firstName
    lastName
    longitude
    latitude
    lastIp
    isAdmin
    isSuperAdmin
    isActive
    associated {
      _id
      companyName
      tradingName
      inscription
      description
      pixKey
      impactedPeople
      foundationDate
      isActive
      cause {
        _id
        name
      }
      otherCause
      address {
        cep
        state
        city
        neighborhood
        street
        number
        complement
      }
      item {
        _id
        name
        price
        category {
          _id
          name
        }
      }
    }
    institution {
      _id
      companyName
      tradingName
      inscription
      description
      pixKey
      impactedPeople
      foundationDate
      isActive
      cause {
        _id
        name
      }
      otherCause
      address {
        cep
        state
        city
        neighborhood
        street
        number
        complement
      }
      item {
        _id
        name
        price
        category {
          _id
          name
        }
      }
    }
    address {
      cep
      state
      city
      neighborhood
      street
      number
      complement
    }
  }
}

mutation {
  createInstitution(
    data: {
      tradingName: "Instituição Teste"
      inscription: "1234567909"
      address: {
        create: {
          cep: "98700-000"
          state: "Rio Grande do Sul"
          city: "Ijuí"
          neighborhood: "Centro"
          street: "Rua do Comércio"
          number: "1234"
        }
      }
      user: { connect: "311546714668401219" }
    }
  ) {
    _id
    tradingName
    inscription
  }
}

mutation {
  createCause(data: { name: "Combate ao abuso infantil e apoio às vítimas" }) {
    _id
    name
  }
}
mutation {
  createCause(data: { name: "Educação de crianças e jovens" }) {
    _id
    name
  }
}
mutation {
  createCause(data: { name: "Crianças desaparecidas" }) {
    _id
    name
  }
}
mutation {
  createCause(data: { name: "Crianças com deficiência" }) {
    _id
    name
  }
}
mutation {
  createCause(data: { name: "Apoio a crianças com câncer" }) {
    _id
    name
  }
}
mutation {
  createCause(data: { name: "Apoio a mulheres vítimas de violência" }) {
    _id
    name
  }
}
mutation {
  createCause(data: { name: "Empoderamento feminino" }) {
    _id
    name
  }
}
mutation {
  createCause(data: { name: "Combate à desigualdade racial" }) {
    _id
    name
  }
}
mutation {
  createCause(data: { name: "Apoio a pessoas em situação de rua" }) {
    _id
    name
  }
}
mutation {
  createCause(data: { name: "Apoio a adultos com câncer" }) {
    _id
    name
  }
}
mutation {
  createCause(data: { name: "Combate à pobreza" }) {
    _id
    name
  }
}
mutation {
  createCause(data: { name: "Inclusão de pessoas com deficiência" }) {
    _id
    name
  }
}
mutation {
  createCause(data: { name: "Apoio a dependentes químicos" }) {
    _id
    name
  }
}
mutation {
  createCause(
    data: { name: "Acolhimento e melhora da qualidade de vida de idosos" }
  ) {
    _id
    name
  }
}
mutation {
  createCause(data: { name: "Defesa dos direitos indígenas" }) {
    _id
    name
  }
}
mutation {
  createCause(data: { name: "Preservação do meio ambiente" }) {
    _id
    name
  }
}
mutation {
  createCause(data: { name: "Ajuda a animais abandonados" }) {
    _id
    name
  }
}
