mutation CreateUser {
  insert_user_one(
    object: {
      email: "johndoe@gmail.com"
      password: "123"
      first_name: "John"
      last_name: "Doe"
      address: {
        data: {
          zip: "98700-000"
          state: "Rio Grande do Sul"
          city: "Ijuí"
          neighborhood: "Centro"
          street: "Rua José Bonifácio"
          number: 987
          complement: "Casa"
        }
      }
    }
  ) {
    id
    email
    address {
      id
      zip
    }
  }
}

mutation CreateCauses {
  insert_cause(
    objects: [
      { name: "Combate ao abuso infantil e apoio às vítimas" }
      { name: "Educação de crianças e jovens" }
      { name: "Crianças desaparecidas" }
      { name: "Crianças com deficiência" }
      { name: "Apoio a crianças com câncer" }
      { name: "Apoio a mulheres vítimas de violência" }
      { name: "Empoderamento feminino" }
      { name: "Combate à desigualdade racial" }
      { name: "Apoio a pessoas em situação de rua" }
      { name: "Apoio a adultos com câncer" }
      { name: "Combate à pobreza" }
      { name: "Inclusão de pessoas com deficiência" }
      { name: "Apoio a dependentes químicos" }
      { name: "Defesa dos direitos indígenas" }
      { name: "Preservação do meio ambiente" }
      { name: "Ajuda a animais abandonados" }
    ]
  ) {
    returning {
      id
      name
    }
  }
}

# ==================== HASURA ACTION EXAMPLE ====================

# Mutation with a single user object to derive an action
mutation CreateUser($object: user_insert_input!) {
  insert_user_one(object: $object) {
    id
    email
    address {
      id
      zip
    }
  }
}

# User data object to send as parameter
# {
#   "object": {
#       "email": "johndoe@gmail.com",
#       "password": "123",
#       "first_name": "John",
#       "last_name": "Doe",
#       "address": {
#         "data": {
#           "zip": "98700-000",
#           "state": "Rio Grande do Sul",
#           "city": "Ijuí",
#           "neighborhood": "Centro",
#           "street": "Rua José Bonifácio",
#           "number": 987,
#           "complement": "Casa"
#         }
#       }
#     }
# }

# Action after be created in Hasura panel
mutation CreateUser($object: CreateUserUserInsertInput!) {
  CreateUser(object: $object) {
    id
    email
  }
}
