SET check_function_bodies = false;
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (1, 'Arroz', '2kg', 9, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (2, 'Feijão', '1kg', 8, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (3, 'Óleo', '1L', 8, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (4, 'Sal', '1kg', 2, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (5, 'Açúcar', '1kg', 5, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (6, 'Café', '500g', 11, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (7, 'Macarrão', '500g', 4, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (8, 'Leite Longa Vida', '1L', 4, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (9, 'Leite em Pó', '400g', 12, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (10, 'Achocolatado', '400g', 6, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (11, 'Macarrão Instantâneo', '400g', 4, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (12, 'Extrato de Tomate', '540g', 7, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (13, 'Leite Condensado', '395g', 5, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (14, 'Sardinhas', '125g', 5, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (15, 'Ervilhas', '500g', 5, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (16, 'Milho', '300g', 6, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (17, 'Salsicha', '500g', 10, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (18, 'Farinha de Mandioca', '1kg', 5, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (19, 'Farinha de Milho', '1kg', 6, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (20, 'Farinha de Trigo', '1kg', 4, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (21, 'Biscoitos Doces ou Salgados', '400g', 5, 1);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (22, 'Sabão em Pedra', '1kg', 12, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (23, 'Sabão em Pó', '800g', 10, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (24, 'Creme Dental', '90g', 4, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (25, 'Sabonete', '150g', 3, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (26, 'Papel Higiênico', '60m C/4', 5, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (27, 'Shampoo', '325ml', 9, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (28, 'Condicionador', '350ml', 12, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (29, 'Absorventes Íntimos', 'C/8', 4, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (30, 'Detergente Líquido', '500ml', 2, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (31, 'Amaciante de Roupas', '2L', 7, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (32, 'Água Sanitária', '2L', 7, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (33, 'Esponja de Aço', 'C/8', 2, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (34, 'Esponja Multiuso', 'C/4', 4, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (35, 'Caixa de Fósforo', 'C/240', 6, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (36, 'Isqueiro', '', 6, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (37, 'Álcool em Gel', '480g', 8, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (38, 'Fraldas', 'C/18', 21, 2);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (39, 'Casaco ou Moletom', '', 60, 3);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (40, 'Calça ou Bermuda', '', 40, 3);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (41, 'Sapato ou Tênis', '', 60, 3);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (42, 'Cobertor ou Acolchoado', '', 60, 3);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (43, 'Colchão', 'Solteiro', 200, 3);
INSERT INTO public.item (id, name, measure, price, category_id) VALUES (44, 'Brinquedo', '', 20, 4);
SELECT pg_catalog.setval('public.item_id_seq', 44, true);
